In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
score_columns=['math score', 'reading score', 'writing score']

In [ ]:
score_columns

['math score', 'reading score', 'writing score']

In [ ]:
df[score_columns].describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
df[score_columns].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [ ]:
df[score_columns].median()

math score       66.0
reading score    70.0
writing score    69.0
dtype: float64

In [ ]:
df[score_columns].mode()

   math score  reading score  writing score
0          65             72             74

In [ ]:
df[score_columns].std()

math score       15.163080
reading score    14.600192
writing score    15.195657
dtype: float64

In [ ]:
df[score_columns].quantile(0.25)

math score       57.00
reading score    59.00
writing score    57.75
Name: 0.25, dtype: float64

In [ ]:
df["Total Score"]=(df["math score"]
                   +df["reading score"]
                   +df["writing score"])

In [ ]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'Total Score'],
      dtype='object')

In [ ]:
df["Percentage"]=(df["Total Score"]/300)*100

In [ ]:
df[["Total Score","Percentage"]].head()

   Total Score  Percentage
0          218   72.666667
1          247   82.333333
2          278   92.666667
3          148   49.333333
4          229   76.333333

In [ ]:
df['Average Score']=df[
    ['math score', 'reading score', 'writing score']
].mean(axis=1)

In [ ]:
df['Pass/Fail']=(
    (df['math score']>=40)&
    (df['reading score']>=40)&
    (df['writing score']>=40)
).map({
    True:'Pass',
    False:'Fail'
})

In [ ]:
Q1=df['math score'].quantile(0.25)
Q3=df['math score'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

In [ ]:
math_outliers=df[
    (df['math score']<lower)|
     (df['math score']>upper)
]

In [ ]:
math_outliers

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Percentage,Average Score,Pass/Fail
17,female,group B,some high school,free/reduced,none,18,32,28,78,26.000000,26.000000,Fail
59,female,group C,some high school,free/reduced,none,0,17,10,27,9.000000,9.000000,Fail
145,female,group C,some college,free/reduced,none,22,39,33,94,31.333333,31.333333,Fail
338,female,group B,some high school,free/reduced,none,24,38,27,89,29.666667,29.666667,Fail
466,female,group D,associate's degree,free/reduced,none,26,31,38,95,31.666667,31.666667,Fail
787,female,group B,some college,standard,none,19,38,32,89,29.666667,29.666667,Fail
842,female,group B,high school,free/reduced,completed,23,44,36,103,34.333333,34.333333,Fail
980,female,group B,high school,free/reduced,none,8,24,23,55,18.333333,18.333333,Fail